package go;

public enum ID {
	PLAYER, SLIME, BAT, BOSS, ENEMY_CRYSTAL, NORMAL_ARROW, EXPLOSIVE_ARROW, PIERCING_ARROW, EXPLOSIVE_ARROW_P, PIERCING_ARROW_P, INVINCIBLE_POTION, GEM, HEALTH, ROCK_THROWER, FIRE_BALL, OBSTACLE, SURVIVAL, ADVENTURE
}
